## Programming Assignment: Бэггинг и случайный лес

In [6]:
from sklearn import datasets
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [8]:
digits_data = datasets.load_digits()
print digits_data.DESCR

Optical Recognition of Handwritten Digits Data Set

Notes
-----
Data Set Characteristics:
    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
http://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each block. This generates
an input matrix of 8x8 where each element is a

In [10]:
digits_data.target, len(digits_data.target)

(array([0, 1, 2, ..., 8, 9, 8]), 1797)

In [11]:
len(digits_data.data)

1797

In [12]:
len(digits_data.data[0])

64

In [13]:
digits_data.data[0]

array([  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.,   0.,   0.,  13.,
        15.,  10.,  15.,   5.,   0.,   0.,   3.,  15.,   2.,   0.,  11.,
         8.,   0.,   0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.,   0.,
         5.,   8.,   0.,   0.,   9.,   8.,   0.,   0.,   4.,  11.,   0.,
         1.,  12.,   7.,   0.,   0.,   2.,  14.,   5.,  10.,  12.,   0.,
         0.,   0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.])

In [14]:
X = digits_data.data
y = digits_data.target

Для оценки качества далее нужно будет использовать **cross_val_score** из **sklearn.cross_validation** с параметром **cv=10**. Эта функция реализует **k-fold cross validation** c k равным значению параметра cv. Мы предлагаем использовать **k=10**, чтобы полученные оценки качества имели небольшой разброс, и было проще проверить полученные ответы. На практике же часто хватает и **k=5**. Функция **cross_val_score** будет возвращать **numpy.ndarray**, в котором будет **k** чисел - качество в каждом из **k** экспериментов k-fold cross validation. Для получения среднего значения (которое и будет оценкой качества работы) вызовите метод **.mean()** у массива, который возвращает **cross_val_score**.

In [16]:
from sklearn import cross_validation, tree

In [17]:
estimator_1 = tree.DecisionTreeClassifier()
result_1 = cross_validation.cross_val_score(estimator_1, X, y, cv=10)
result_1

array([ 0.78378378,  0.84699454,  0.81767956,  0.80555556,  0.77653631,
        0.89385475,  0.88268156,  0.8258427 ,  0.85310734,  0.83522727])

In [18]:
result_1.mean()

0.83212633725570928

In [23]:
def write_answer(number, value):
    with open("answer{}.txt".format(number), "w") as fout:
        fout.write(str(value))

In [24]:
write_answer(1, result_1.mean())

In [20]:
from sklearn import ensemble

In [21]:
estimator_2 = ensemble.BaggingClassifier(estimator_1, n_estimators=100)
result_2 = cross_validation.cross_val_score(estimator_2, X, y, cv=10)
result_2

array([ 0.86486486,  0.95628415,  0.91712707,  0.94444444,  0.92178771,
        0.97765363,  0.96089385,  0.92134831,  0.85875706,  0.91477273])

In [22]:
result_2.mean()

0.92379338336950645

In [25]:
write_answer(2, result_2.mean())


In [32]:
import numpy as np
optimal_num_features = int(np.sqrt(X.shape[1]))
print optimal_num_features
estimator_3 = ensemble.BaggingClassifier(estimator_1, n_estimators=100, max_features=optimal_num_features)
result_3 = cross_validation.cross_val_score(estimator_3, X, y, cv=10)
result_3

8


array([ 0.9027027 ,  0.96174863,  0.9558011 ,  0.9       ,  0.93854749,
        0.94413408,  0.97206704,  0.98876404,  0.88135593,  0.90340909])

In [33]:
result_3.mean()

0.9348530112963116

In [34]:
write_answer(3, result_3.mean())

In [36]:
estimator_4_0 = tree.DecisionTreeClassifier(max_features=optimal_num_features)
estimator_4 = ensemble.BaggingClassifier(estimator_4_0, n_estimators=100)
result_4 = cross_validation.cross_val_score(estimator_4, X, y, cv=10)
result_4

array([ 0.9027027 ,  0.97814208,  0.93370166,  0.96666667,  0.94972067,
        0.97765363,  0.97765363,  0.97191011,  0.93220339,  0.9375    ])

In [37]:
result_4.mean()

0.95278545384816182

In [38]:
write_answer(4, result_4.mean())

In [40]:
from sklearn.ensemble import RandomForestClassifier
estimator_rf = RandomForestClassifier(n_estimators=100)
result_rf = cross_validation.cross_val_score(estimator_rf, X, y, cv=10)
result_rf.mean()

0.95335172681076619

In [49]:
import matplotlib as plt

In [48]:
tree_number_list = np.arange(1, 200, 20)

score_mean = []
for idx in tree_number_list:
    estimator_tree_number = RandomForestClassifier(n_estimators=idx)
    result_rf = cross_validation.cross_val_score(estimator_tree_number, X, y, cv=5)
    score_mean.append(result_rf.mean())


score_mean

[0.68892515426550016,
 0.92163783393014875,
 0.93328982216092204,
 0.93602937465987457,
 0.93996668031050734,
 0.93770579171353907,
 0.94105141056984976,
 0.93888039015114111,
 0.93829534223542077,
 0.93941120242135678]

In [53]:
feature_number_list = np.arange(4, X.shape[1], 4)

score_mean = []
for idx in feature_number_list:
    estimator_feature_number = RandomForestClassifier(n_estimators=30, max_features=idx)
    result_rf = cross_validation.cross_val_score(estimator_feature_number, X, y, cv=5)
    score_mean.append(result_rf.mean())


score_mean

[0.92385916376061716,
 0.93204403776138511,
 0.92659692410689909,
 0.91938324645967973,
 0.93047502185842657,
 0.92763665247318006,
 0.92265292686997036,
 0.91659375118395603,
 0.91266924735948829,
 0.91096707823089884,
 0.9176466518079851,
 0.91650732175515459,
 0.91714792659608901,
 0.9109560133627056,
 0.90871783491866798]

In [54]:
depth_number_list = np.arange(1, 20, 1)

score_mean = []
for idx in depth_number_list:
    estimator_depth_number = RandomForestClassifier(n_estimators=30, max_depth=idx)
    result_rf = cross_validation.cross_val_score(estimator_depth_number, X, y, cv=5)
    score_mean.append(result_rf.mean())


score_mean

[0.65072493364530237,
 0.76844277155159901,
 0.82540777265295306,
 0.86364416582975101,
 0.88654539921005659,
 0.90655168753770377,
 0.91825599739806196,
 0.91827625456861384,
 0.91723206504625598,
 0.92272551195370656,
 0.93268517255064154,
 0.9277652892639674,
 0.93329663181387235,
 0.9316330605234624,
 0.92831453387258411,
 0.93274839455767078,
 0.92828194326182312,
 0.92603341698795005,
 0.92605355988844162]

In [55]:
write_answer(5, "2 3 4")